-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "deDE")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Abkürzungen für den Tooltip ändern"
L["Chatframe Messages"] = "Chatnachrichten"
L["Color names by class"] = "Namen nach Klasse färben"
L["DB_VERSION_UPGRADE_PURGE"] = "Datenbanklöschung wegen struktureller Änderung der Daten. Dies wird empfohlen, damit keine Fehler auftreten, die von Daten älterer Versionen herrühren können. Jeder Charakter muss erneut angemeldet werden, damit seine Daten angezeigt werden."
L["Diff"] = "Modus"
L["Free raid color"] = "Farbe für freie Schlachtzüge"
L["FREE_RAID_DESC"] = "Farbe auswählen, die verwendet werden soll, falls ein Charakter keine ID für diese Instanz besitzt"
L["General Settings"] = "Allgemeine Optionen"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "Falls der Charakter die 'Sieg in Tausendwinter' Weekly PvP Quest absolviert hat."
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "Falls der Charakter die Raid Weekly aus Dalaran absolviert hat. "
L["Instance Abbreviations"] = "Instanzabkürzung"
L["No saved raids found"] = "Keine zugewiesenen Schlachtzüge gefunden"
L["Raid"] = "Instanz"
L["Regardles of any saved instances"] = "Unabhängig von gespeicherten Instanzen" -- Needs review
L["Saved raid color"] = "Farbe für bereits zugewiesene Schlachtzüge"
L["SAVED_RAID_DESC"] = "Farbe auswählen, die verwendet werden soll, falls ein Charakter bereits eine ID für diese Instanz besitzt"
L["Show 5-man instances"] = "Zeige 5-Mann-Instanzen"
L["Show all chars"] = "Zeige alle Charakter"
L["Show character realms"] = "Realms anzeigen"
L["Show minimap button"] = "Minimap-Symbol anzeigen"
L["Show Realm Headers"] = "Zeige den Realm an"
L["SHOW_REALMLINES_DESC"] = "Trenne optisch die Charaktere anderer Realms im Tooltip"
L["Show the Ailo minimap button"] = "Das Ailo-Minimap-Symbol anzeigen"
L["Size"] = "Größe"
L["Tooltip abbreviation used for heroic raids"] = "Abkürzung für \"heroische\" Schlachtzüge im Tooltip"
L["Tooltip abbreviation used for nonheroic raids"] = "Abkürzung für \"nicht-heroische\" Schlachtzüge im Tooltip"
L["Track 'Daily Heroic'"] = "Zeige 'Daily HC'"
L["TRACK_DAILY_HEROIC_DESC"] = "Zeige im Tooltip ob der Charakter die heroische Dungeon Daily heute abgeschlossen hat"
L["Track PvP daily"] = "Zeige PvP Daily"
L["Track 'Weekly Raid'"] = "Zeige Raid Weekly"
L["Track 'WG Victory'"] = "Zeige TWS"
L["Updating data for current player."] = "Aktualisierung der Daten für aktuellen Spieler"
L["Use !ClassColors"] = "Klassenfarben verwenden"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "!ClassColors-Addon für Klassenfarben im Tooltip verwenden"
L["Wipe Database"] = "Datenbank löschen"

L["Track 'Event boss'"] = "Zeige 'Event Boss'"
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "Während einem World Event, zeige ob der Charakter die 'Event Boss' Daily heute abgeschlossen hat"

L["showOnlyWrathRaids"] = "Zeige nur WotLK Raids"
L["showOnlyWrathRaids_DESC"] = "Es werden ausschließlich WotLK Schlachtzüge angezeigt und die restlichen Schlachtzug-IDs werden ignoriert"
