-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "esES")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Change the abbreviations used in the tooltip" -- Requires localization
L["Chatframe Messages"] = "Chatmessages" -- Requires localization
L["Color names by class"] = "Color names by class" -- Requires localization
L["DB_VERSION_UPGRADE_PURGE"] = "Purging database because of a structural change. This is to ensure there are now errors caused by data from older versions. You'll have to login with every char again to get its data shown." -- Requires localization
L["Diff"] = "Diff" -- Requires localization
L["Free raid color"] = "Free raid color" -- Requires localization
L["FREE_RAID_DESC"] = "Set the color used to show when a char is free to raid this instance" -- Requires localization
L["General Settings"] = "General Settings" -- Requires localization
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest" -- Requires localization
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "If the character has done the 'Weekly Raid' you get in Dalaran" -- Requires localization
L["Instance Abbreviations"] = "Instance Abbreviations" -- Requires localization
L["No saved raids found"] = "No saved raids found" -- Requires localization
L["Raid"] = "Raid" -- Requires localization
L["Regardles of any saved instances"] = "Regardles of any saved instances" -- Requires localization
L["Saved raid color"] = "Saved raid color" -- Requires localization
L["SAVED_RAID_DESC"] = "Set the color used to show when a char is already locked out of this instance" -- Requires localization
L["Show 5-man instances"] = "Show 5-man instances" -- Requires localization
L["Show all chars"] = "Show all chars" -- Requires localization
L["Show character realms"] = "Show character realms" -- Requires localization
L["Show minimap button"] = "Show minimap button" -- Requires localization
L["Show Realm Headers"] = "Show Realm Headers" -- Requires localization
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip" -- Requires localization
L["Show the Ailo minimap button"] = "Show the Ailo minimap button" -- Requires localization
L["Size"] = "Size" -- Requires localization
L["Tooltip abbreviation used for heroic raids"] = "Tooltip abbreviation used for heroic raids" -- Requires localization
L["Tooltip abbreviation used for nonheroic raids"] = "Tooltip abbreviation used for nonheroic raids" -- Requires localization
L["Track 'Daily Heroic'"] = "Track 'Daily Heroic'" -- Requires localization
L["TRACK_DAILY_HEROIC_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic' or not" -- Requires localization
L["Track PvP daily"] = "Track PvP daily" -- Requires localization
L["Track 'Weekly Raid'"] = "Track 'Weekly Raid'" -- Requires localization
L["Track 'WG Victory'"] = "Track 'WG Victory'" -- Requires localization
L["Updating data for current player."] = "Updating data for current player." -- Requires localization
L["Use !ClassColors"] = "Use !ClassColors" -- Requires localization
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Use !ClassColors addon for class colors used to color the names in the tooltip" -- Requires localization
L["Wipe Database"] = "Wipe Database" -- Requires localization

L["Track 'Event boss'"] = true -- Requires localization
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "During a World Event, show a column in the tooltip indicating if a character has done the 'Event Boss instance'" -- Requires localization

