-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "frFR")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Changer les abréviations utilisées dans la bulle d'aide."
L["Chatframe Messages"] = "Chatmessages" -- Requires localization
L["Color names by class"] = "Colorer les noms par classe"
L["DB_VERSION_UPGRADE_PURGE"] = "Purging database because of a structural change. This is to ensure there are now errors caused by data from older versions. You'll have to login with every char again to get its data shown." -- Requires localization
L["Diff"] = "Diff" -- Requires localization
L["Free raid color"] = "Free raid color" -- Requires localization
L["FREE_RAID_DESC"] = "Set the color used to show when a char is free to raid this instance" -- Requires localization
L["General Settings"] = "Paramètres généraux"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest" -- Requires localization
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "If the character has done the 'Weekly Raid' you get in Dalaran" -- Requires localization
L["Instance Abbreviations"] = "Abréviations des instances"
L["No saved raids found"] = "No saved raids found" -- Requires localization
L["Raid"] = true
L["Regardles of any saved instances"] = "Regardles of any saved instances" -- Requires localization
L["Saved raid color"] = "La couleur du raid est sauvegardée"
L["SAVED_RAID_DESC"] = "Set the color used to show when a char is already locked out of this instance" -- Requires localization
L["Show 5-man instances"] = "Montrer les instances à 5"
L["Show all chars"] = "Montrer tous les personnages"
L["Show character realms"] = "Montrer le royaume des personnages."
L["Show minimap button"] = "Montrer le bouton de la minicarte"
L["Show Realm Headers"] = "Show Realm Headers" -- Requires localization
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip" -- Requires localization
L["Show the Ailo minimap button"] = "Show the Ailo minimap button" -- Requires localization
L["Size"] = "Taille"
L["Tooltip abbreviation used for heroic raids"] = "Abréviation utilisée pour les raids en mode héroïque"
L["Tooltip abbreviation used for nonheroic raids"] = "Abréviation utilisée pour les raids en mode normal"
L["Track 'Daily Heroic'"] = "Track 'Daily Heroic'" -- Requires localization
L["TRACK_DAILY_HEROIC_DESC"] = "Show a column in the tooltip indicating if a character has done the 'Daily Heroic' or not" -- Requires localization
L["Track PvP daily"] = "Track PvP daily" -- Requires localization
L["Track 'Weekly Raid'"] = "Track 'Weekly Raid'" -- Requires localization
L["Track 'WG Victory'"] = "Track 'WG Victory'" -- Requires localization
L["Updating data for current player."] = "Mise à jour des données pour le joueur actuel en cours."
L["Use !ClassColors"] = "Utiliser l'addon !ClassColors"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Utiliser l'addon !ClassColors pour les couleurs de classe utilisées pour colorer les noms dans l'info-bulle."
L["Wipe Database"] = "Remise à zéro de la base de données"

L["Track 'Event boss'"] = true -- Requires localization
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "During a World Event, show a column in the tooltip indicating if a character has done the 'Event Boss instance'" -- Requires localization
