-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "koKR")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "툴팁에서 던전 이름을 표시할 때 사용할 약칭을 설정"
L["Chatframe Messages"] = "채팅창 메세지"
L["Color names by class"] = "이름에 직업 색상 사용"
L["DB_VERSION_UPGRADE_PURGE"] = "정보가 저장되는 방식이 바뀌어 이전 내용을 삭제합니다. 기존 버전의 저장 내용으로 인해 오류가 발생하지 않기 위함입니다. 이 애드온을 사용하는 캐릭터를 다시 접속할때마다 새로운 저장 방식으로 갱신됩니다."
L["Diff"] = "난이도"
L["Free raid color"] = "귀속되지 않은 던전"
L["FREE_RAID_DESC"] = "아직 귀속되지 않은 던전을 표시할 색상을 설정합니다"
L["General Settings"] = "기본 설정"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "주간 pvp 퀘스트인 '겨울손아귀에서의 승리'의 완료 여부를 표시합니다"
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "'주간 퀘스트'를 완료하였다면, 달라란 NPC에게 완료를 받으십시오."
L["Instance Abbreviations"] = "던전 약칭"
L["No saved raids found"] = "귀속된 던전이 없습니다"
L["Raid"] = "던전"
L["Regardles of any saved instances"] = "Regardles of any saved instances" -- Requires localization
L["Saved raid color"] = "귀속된 던전"
L["SAVED_RAID_DESC"] = "귀속된 던전을 표시할 색상을 설정합니다"
L["Show 5-man instances"] = "5인 던전 보이기"
L["Show all chars"] = "Show all chars" -- Requires localization
L["Show character realms"] = "캐릭터의 서버명 보이기"
L["Show minimap button"] = "미니맵 버튼 보이기"
L["Show Realm Headers"] = "서버 이름 보이기"
L["SHOW_REALMLINES_DESC"] = "툴팁으로 보여질 때, 캐릭터 이름 위에 해당 서버의 이름을 보여줍니다"
L["Show the Ailo minimap button"] = "미니맵에 Ailo 버튼을 표시합니다"
L["Size"] = "인원"
L["Tooltip abbreviation used for heroic raids"] = "영웅 던전을 표시할 약칭"
L["Tooltip abbreviation used for nonheroic raids"] = "일반 던전을 표시할 약칭"
L["Track 'Daily Heroic'"] = "'일일 무작위 영웅' 추적"
L["TRACK_DAILY_HEROIC_DESC"] = "'일일 무작위 영웅 던전'을 완료한 캐릭터의 이름 앞에 서리의 문장 아이콘을 보입니다" -- Needs review
L["Track PvP daily"] = "'일일 무작위 전장' 추적"
L["Track 'Weekly Raid'"] = "'주간 퀘스트' 추적"
L["Track 'WG Victory'"] = "'겨울손아귀에서의 승리' 추적"
L["Updating data for current player."] = "현재 캐릭터에 대한 정보를 업데이트합니다."
L["Use !ClassColors"] = "!ClassColor 설정을 사용"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "!ClassColors 애드온을 사용중이라면 툴팁에 직업 색상을 표시할 때 !ClassColors 설정 내용대로 표시합니다"
L["Wipe Database"] = "귀속 정보 지우기"

L["Track 'Event boss'"] = true -- Requires localization
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "During a World Event, show a column in the tooltip indicating if a character has done the 'Event Boss instance'" -- Requires localization
