-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "ruRU")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "Изменить сокращения во всплывающих подсказках"
L["Chatframe Messages"] = "Сообщения в чате"
L["Color names by class"] = "Имена цветом класса"
L["DB_VERSION_UPGRADE_PURGE"] = "Очищаю БД в связи с изменениями структуры. Необходимо для предотвращения ошибок, связанных с сохраненными данными от предыдущих версий. Вы должны снова зайти в игру всеми персонажами для сбора данных."
L["Diff"] = "Сложность"
L["Free raid color"] = "Цвет доступных рейдов"
L["FREE_RAID_DESC"] = "Выберите цвет, используемый для отображения доступных рейдов"
L["General Settings"] = "Общие настройки"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest" -- Requires localization
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "If the character has done the 'Weekly Raid' you get in Dalaran" -- Requires localization
L["Instance Abbreviations"] = "Сокращения подземелий"
L["No saved raids found"] = "Нет сохраненных рейдов"
L["Raid"] = "Рейд"
L["Regardles of any saved instances"] = "Regardles of any saved instances" -- Requires localization
L["Saved raid color"] = "Цвет сохраненных рейдов"
L["SAVED_RAID_DESC"] = "Выберите цвет, используемый для отображения сохраненных рейдов"
L["Show 5-man instances"] = "Показывать подземелья на 5 игроков"
L["Show all chars"] = "Show all chars" -- Requires localization
L["Show character realms"] = "Показывать игровой мир персонажа "
L["Show minimap button"] = "Показать иконку у мини-карты"
L["Show Realm Headers"] = "Show Realm Headers" -- Requires localization
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip" -- Requires localization
L["Show the Ailo minimap button"] = "Закрепить иконку у мини-карты"
L["Size"] = "Размер"
L["Tooltip abbreviation used for heroic raids"] = "Сокращенное обозначение для героич. рейдов"
L["Tooltip abbreviation used for nonheroic raids"] = "Сокращенное обозначение для нормал рейдов"
L["Track 'Daily Heroic'"] = "Отслеживать \"рандомлик\""
L["TRACK_DAILY_HEROIC_DESC"] = "Если персонаж сегодня уже выполнил \"Случайное подземелье, героический\" во всплывающей подсказке будет отображаться \"Эмблема Льда\" перед его именем" -- Needs review
L["Track PvP daily"] = "Track PvP daily" -- Requires localization
L["Track 'Weekly Raid'"] = "Track 'Weekly Raid'" -- Requires localization
L["Track 'WG Victory'"] = "Track 'WG Victory'" -- Requires localization
L["Updating data for current player."] = "Обновляю данные для текущего персонажа"
L["Use !ClassColors"] = "Использовать цвета классов"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "Использовать аддон !ClassColors для отображения имени персонажа цветом класса во всплывающей подсказке"
L["Wipe Database"] = "Очистить БД"
