-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "zhCN")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "更改提示缩写"
L["Chatframe Messages"] = "聊天框信息"
L["Color names by class"] = "职业颜色"
L["DB_VERSION_UPGRADE_PURGE"] = "由于结构变化而清除数据库。当前错误因旧版本数据所造成。必须先登录每个角色再次获得的数据显示。"
L["Diff"] = "差异"
L["Free raid color"] = "可用团队颜色"
L["FREE_RAID_DESC"] = "设置用来显示角色可用团队副本的颜色"
L["General Settings"] = "一般设置"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "If the character has done the 'Victory in Wintergrasp' weekly pvp quest" -- Requires localization
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "If the character has done the 'Weekly Raid' you get in Dalaran" -- Requires localization
L["Instance Abbreviations"] = "副本缩写"
L["No saved raids found"] = "没有找到已保存团队"
L["Raid"] = "团队"
L["Regardles of any saved instances"] = "Regardles of any saved instances" -- Requires localization
L["Saved raid color"] = "已保存团队颜色"
L["SAVED_RAID_DESC"] = "设置用来显示角色已保存团队副本的颜色"
L["Show 5-man instances"] = "显示5人副本"
L["Show all chars"] = "Show all chars" -- Requires localization
L["Show character realms"] = "Show character realms" -- Requires localization
L["Show minimap button"] = "显示迷你地图图标"
L["Show Realm Headers"] = "Show Realm Headers" -- Requires localization
L["SHOW_REALMLINES_DESC"] = "Show a headerline before chars from another realm beginn in the tooltip" -- Requires localization
L["Show the Ailo minimap button"] = "显示 Ailo 迷你地图图标"
L["Size"] = "尺寸"
L["Tooltip abbreviation used for heroic raids"] = "英雄团队提示缩写"
L["Tooltip abbreviation used for nonheroic raids"] = "非英雄团队提示缩写"
L["Track 'Daily Heroic'"] = "追踪 '日常英雄'"
L["TRACK_DAILY_HEROIC_DESC"] = "如果角色已经完成今天的 '日常英雄', 提示信息中将在名字前显示一个寒冰纹章" -- Needs review
L["Track PvP daily"] = "Track PvP daily" -- Requires localization
L["Track 'Weekly Raid'"] = "Track 'Weekly Raid'" -- Requires localization
L["Track 'WG Victory'"] = "Track 'WG Victory'" -- Requires localization
L["Updating data for current player."] = "更新当前角色数据"
L["Use !ClassColors"] = "使用 !ClassColors"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "提示使用 !ClassColors 插件的职业颜色"
L["Wipe Database"] = "灭团数据库"

L["Track 'Event boss'"] = true -- Requires localization
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "During a World Event, show a column in the tooltip indicating if a character has done the 'Event Boss instance'" -- Requires localization
