-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/ailo/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Ailo", "zhTW")
if not L then return end

L["Change the abbreviations used in the tooltip"] = "修改簡稱"
L["Chatframe Messages"] = "對話框訊息"
L["Color names by class"] = "角色名稱依職業著色"
L["DB_VERSION_UPGRADE_PURGE"] = "系統已更新，為確保舊版資料造成UI錯誤，將清空舊版資料庫."
L["Diff"] = "難度"
L["Free raid color"] = "無進度顏色"
L["FREE_RAID_DESC"] = "設定角色在該副本沒有進度時的顯示顏色"
L["General Settings"] = "一般設定"
L["If the character has done the 'Victory in Wintergrasp' weekly pvp quest"] = "追蹤冬握湖每週任務:冬握湖勝利是否完成"
L["If the character has done the 'Weekly Raid' you get in Dalaran"] = "追蹤達拉然每週團隊任務是否完成"
L["Instance Abbreviations"] = "副本簡稱"
L["No saved raids found"] = "沒有任何團隊記錄"
L["Raid"] = "團隊"
L["Regardles of any saved instances"] = "忽略已儲存的副本進度"
L["Saved raid color"] = "有進度顏色"
L["SAVED_RAID_DESC"] = "設定角色已有該副本進度時的顯示顏色"
L["Show 5-man instances"] = "顯示五人副本進度"
L["Show all chars"] = "顯示所有角色"
L["Show character realms"] = "顯示角色所在伺服器"
L["Show minimap button"] = "顯示小地圖按鈕"
L["Show Realm Headers"] = "顯示伺服器名稱"
L["SHOW_REALMLINES_DESC"] = "在不同伺服器角色前顯示伺服器名稱"
L["Show the Ailo minimap button"] = "顯示小地圖按鈕"
L["Size"] = "類別"
L["Tooltip abbreviation used for heroic raids"] = "英雄模式簡稱"
L["Tooltip abbreviation used for nonheroic raids"] = "普通模式簡稱"
L["Track 'Daily Heroic'"] = "追蹤每日英雄進度"
L["TRACK_DAILY_HEROIC_DESC"] = "追蹤每日隨機英雄副本是否完成"
L["Track PvP daily"] = "追蹤每日隨機戰場"
L["Track 'Weekly Raid'"] = "追蹤每週團隊任務"
L["Track 'WG Victory'"] = "追蹤每週:冬握湖勝利"
L["Updating data for current player."] = "更新當前角色資訊"
L["Use !ClassColors"] = "使用職業顏色"
L["Use !ClassColors addon for class colors used to color the names in the tooltip"] = "將角色名稱依職業顯示不同顏色"
L["Wipe Database"] = "清除資料庫"

L["Track 'Event boss'"] = true -- Requires localization
L["TRACK_DAILY_EVENT_BOSS_DESC"] = "During a World Event, show a column in the tooltip indicating if a character has done the 'Event Boss instance'" -- Requires localization
